
services:
  mongodb:
    image: mongo:6.0
    container_name: sustainability-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: sustainability_dashboard
    networks:
      - sustainability-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sustainability-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - MONGODB_DATABASE=sustainability_dashboard
      - BACKEND_HOST=0.0.0.0
      - BACKEND_PORT=8000
      - CORS_ORIGINS=http://localhost:3000,http://localhost:5173
      - SCHEDULER_INTERVAL_MINUTES=1
    depends_on:
      - mongodb
    networks:
      - sustainability-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sustainability-frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - sustainability-network

volumes:
  mongodb_data:

networks:
  sustainability-network:
    driver: bridge